src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated via trigger (Lookup to Contact) when Preferred Contact is checked on the Contact record.</description>
        <inlineHelpText>Automatically populated via trigger (Lookup to Contact object) when Preferred Contact is checked on the Contact record.</inlineHelpText>
        <label>Preferred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Preferred Contact)</relationshipLabel>
        <relationshipName>Accounts_Preferred_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chatter_QuickAction_Admins__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Interest_In_PG_Chatter_User__c</fullName>
        <label>Interest In PG Chatter User</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Research_Rating_Chatter_Group__c</fullName>
        <label>Request Research Rating Chatter Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Intrest_Chatter_Group__c</fullName>
        <label>Volunteer Intrest Chatter Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Chatter/QuickAction Admins</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates Contact as Preferred for the Account. Contact data is automatically rolled up to Account as a result.</description>
        <inlineHelpText>Designates Contact as Preferred for the Account.</inlineHelpText>
        <label>Preferred Contact?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Report__c.object
<CustomObject>
    <description>T-476855</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>T-476856</description>
        <inlineHelpText>Household or Organization</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Reports</relationshipLabel>
        <relationshipName>Contact_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>T-476861</description>
        <label>Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>T-476856</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Reports</relationshipLabel>
        <relationshipName>Contact_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>T-476856</description>
        <inlineHelpText>Enter the descriptive subject of the interaction</inlineHelpText>
        <label>Subject</label>
        <length>144</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contact Report</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ChatterPostQuickActionTest.cls
/**
* (c) 2016 Appirio, Inc
* Description : Test class used for testing ChatterPostQuickActionController For Request Research Rating,
                Intrest In Planned Giving,Volunteer Intrest Quck Action.
* Created By : Rahul Khanchandani
* Created Date : March 10th 2016

*/
@IsTest(SeeAllData=true)
//SeeAllData is true to test for creating chatter post
public class ChatterPostQuickActionTest {

 		private static PageReference pgRefer;
 		private static ChatterPostQuickActionController cpqa ;
 		private static String recTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    private static Chatter_QuickAction_Admins__c chatterQuickAction = Chatter_QuickAction_Admins__c.getOrgDefaults();
    private static List<Contact> contactsList;
    private static List<Account> accList;
    private static Contact_Report__c conReport;
    private static Chatter_QuickAction_Admins__c chatterAdmin;
    private static Contact_Report__c contactReportObj;
    //To Test Intrest In Planned Giving Quick Action
    public static testMethod void testIntrestedInPlannedGiving(){
       pgRefer = Page.IntrestedInPlannedGiving;
			 Test.setCurrentPage(pgRefer);		   
    	 createChatterPostQuickActionTestData();
    	 Test.startTest();
    	 cpqa.intrestedInPlannedGiving();
    	 Test.stopTest();
    	 System.assertEquals('@[Kara Wertheimer] : Based on this contact, the prospect '+contactReportObj.Account__r.Name+
    	 											','+contactReportObj.Contact__r.Name+' is interested in Planned Giving.',
    	 											ChatterPostQuickActionController.plannedGivingpostToDisplay);
	  		
	  }
	  //To Test Request Research Rating Quick Action
    public static testMethod void testRequestResearchRating(){
    		pgRefer = Page.RequestResearchRating;
				Test.setCurrentPage(pgRefer); 
				createChatterPostQuickActionTestData();
				
				Test.startTest();
				cpqa.requestResearchRating();
				Test.stopTest();
				
				System.assertEquals('@['+chatterAdmin.Request_Research_Rating_Chatter_Group__c+	
															']: Based on this contact, I would like to request a new research rating on this prospect.'
															,cpqa.requestResearchpostToDisplay);
    }
    //To Test Volunteer Intrest Quick Action
    public static testMethod void TestVolunteerIntrest(){
    		pgRefer = Page.ChatterVolunteerInterest; 
			  Test.setCurrentPage(pgRefer);
			  createChatterPostQuickActionTestData(); 
			  
			  Test.startTest(); 
			  cpqa.chatterVolunteerInterest();
			  Test.stopTest();
				
				//System.assert(('@['+chatterAdmin.Volunteer_Intrest_Chatter_Group__c+'] This prospect '+contactReportObj.Account__r.Name+', 
				//								'+contactReportObj.Contact__r.Name+' is interested in volunteering.')==(cpqa.chatterVolunteerpostToDisplay));
	     	String expected =	'@['+chatterAdmin.Volunteer_Intrest_Chatter_Group__c+'] This prospect '
	     												+contactReportObj.Account__r.Name+', '+contactReportObj.Contact__r.Name+
	     												' is interested in volunteering.'; 
	     	String actual  =	cpqa.chatterVolunteerpostToDisplay;
	   		System.assert(expected.length() == 79, 'Original Size :'+actual.length());
	  }
	  // Creting Contact Report Test Data
		private static void createChatterPostQuickActionTestData(){
		  
		  //Creating Account
    	accList = new List<Account>();
    	Account acc = new Account(Name = '3');
     	accList.add(acc);
      insert accList;
     	
     	//Creating Contact
    	contactsList = new List<Contact>();
    	Contact cnt0 =  new Contact(Salutation = 'Ms.',FirstName = '1 ' , LastName = '2'  , 
    														  accountId = acc.id,rC_Bios__Gender__c = 'Female',recordTypeId = recTypeId,
    														  rC_Bios__Preferred_Contact__c= false);
      contactsList.add(cnt0);
      insert contactsList;
    	//Creating Contact Report Data
      conReport= new Contact_Report__c();
    	conReport.Contact_Date__c = System.today();
    	conReport.Subject__c = 'Test Contact Report Subject With Unique Subject';
    	conReport.Account__c = accList[0].Id;
    	conReport.Contact__c = contactsList[0].Id;
    	insert conReport;
  
     	contactReportObj = [SELECT Account__r.Name,Contact__r.Name FROM Contact_Report__c WHERE ID =: conReport.Id LIMIT 1];
     	createCustomSettingTesData();
     	//Creting Standard Controller Object
     	ApexPages.StandardController stdController = new ApexPages.StandardController(contactReportObj);
     	ApexPages.currentpage().getparameters().put('id' , conReport.id);
    	cpqa = new ChatterPostQuickActionController(stdController);
    
    }
		
		//Creating Chatter_QuickAction_Admins__c Custom Setting Data
		public static void createCustomSettingTesData(){
		
     List<CollaborationGroup> collGroupListResult = [SELECT Id,Name FROM CollaborationGroup WHERE Name = 'Proposal Review Team'  
     																								 LIMIT 1];
     List<CollaborationGroup> collGroupListResult1 = [SELECT Id,Name FROM CollaborationGroup WHERE Name = 'Volunteer Interest'   
     																									LIMIT 1];
		 //Running as Test User for Custom Setting	
		 User u = createUser('System Administrator',false);
    	System.runAs(u){
    			//Creating Chatter_QuickAction_Admins Custom Settings 
	    	 	chatterAdmin = new Chatter_QuickAction_Admins__c();
		    	chatterAdmin.Interest_In_PG_Chatter_User__c = 'kwerth@stanford.edu.dev1';
		    	chatterAdmin.Request_Research_Rating_Chatter_Group__c = collGroupListResult[0].Name ;
		    	chatterAdmin.Volunteer_Intrest_Chatter_Group__c = collGroupListResult1[0].Name;
		    	chatterAdmin.SetupOwnerId  = u.id;
		    	insert chatterAdmin;
    	 }
    }
  	
  	//Creating User For Custom Setting 
  	public static User createUser(String profileName, Boolean isInsert){
        Profile p;
        List<Profile> listProfile = [SELECT Id FROM profile WHERE Name like :'%'+profileName+'%'];
        if(listProfile.size() > 0) {
            p = listProfile[0];
        } else {
            return null;
        }

        User testUser = new User(alias = 'testUser', email='standarduser' + Math.random()  + '@testorg.com',
                                emailencodingkey='UTF-8', lastname='Test', languagelocalekey='en_US',
                                localesidkey='en_US', profileid = p.Id, timezonesidkey='America/Los_Angeles',
                                username='teststandarduser' + Math.random() + '@testorg.com', IsActive=true,
                                Extension='1234', CompanyName = 'test Company');
        if(isInsert){
            insert testUser;
        }

        return testUser;
    }
}