src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Manually populated field indicating is this account active?</description>
        <inlineHelpText>Is this account active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated via trigger (Lookup to Contact) when Preferred Contact is checked on the Contact record.</description>
        <inlineHelpText>Automatically populated via trigger (Lookup to Contact object) when Preferred Contact is checked on the Contact record.</inlineHelpText>
        <label>Preferred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Preferred Contact)</relationshipLabel>
        <relationshipName>Accounts_Preferred_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Secondary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated via trigger (Lookup to Contact) when Secondary Contact is checked on the Contact record.</description>
        <inlineHelpText>Automatically populated via trigger (Lookup to Contact) when Secondary Contact is checked on the Contact record.</inlineHelpText>
        <label>Secondary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Secondary Contact)</relationshipLabel>
        <relationshipName>Accounts_Secondary_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Single_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>S-340070 - This Field is used to store the Single household that a Single contact is in.  It is used in casethe user gets married and later divorced as a pointer to their old single household.</description>
        <label>Single Household</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Household Account does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <infoMessage>Select the Contact&apos;s Single Household</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Single Contact</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field directly populated by trigger reflecting thids account is active.</description>
        <inlineHelpText>Is this Contact active?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Marital_Status__c</fullName>
        <description>Manually populated field indicating Contact&apos;s marital status.</description>
        <inlineHelpText>Indicates Contact&apos;s marital status.</inlineHelpText>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Marital Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domestic Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formerly Married/Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married At Death</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widowed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates Contact as Preferred for the Account. Contact data is automatically rolled up to Account as a result.</description>
        <inlineHelpText>Designates Contact as Preferred for the Account.</inlineHelpText>
        <label>Preferred Contact?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Secondary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Automatically populated via trigger when Secondary Contact is selecteed on the Account Manage Contacts Page.</description>
        <inlineHelpText>Indicates this Contact is the secondary Contact for their Account.</inlineHelpText>
        <label>Secondary Contact?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MarriageComponentControllerTest.cls
/********************************************************************************************
* Apex Class Name: MarriageComponentControlleTest
* Author: Rahul Khanchandani (Appirio)
* Date: [04/04/2016]
* Requirement Description: Test Class for MarriageComponentControlle (T-489404/S-372714)
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
@isTest
public class MarriageComponentControllerTest {
 
 public static testMethod void test(){
	MarriageComponentController mcc = new MarriageComponentController();
 	PageReference myPage = new Pagereference('/apex/Manage_Life_Event');
 	Test.setCurrentPage(myPage);  
 	Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
 	Account acc = new Account(Name = 'Test',RecordTypeId = devRecordTypeId,rC_Bios__Active__c= true);
 	insert acc;
 	Account acc1 = new Account(Name = 'Test Acc',RecordTypeId = devRecordTypeId);
 	insert acc1;
 	List<Contact> conList = new List<Contact>();
 	
 	  Contact con = new Contact(Salutation = 'Ms.',LastName = 'xyz',rC_Bios__Gender__c = 'Female',AccountId = acc.Id);
      conList.add(con);
      Contact conRecord = new Contact(Salutation = 'Mr.',LastName = 'abc',rC_Bios__Gender__c = 'Male',AccountId = acc1.Id,rC_Bios__Preferred_Contact__c = true);
      conList.add(conRecord);
      
      insert conList;
      mcc.cont = new Contact(Salutation = 'Ms.',LastName = 'xyz',rC_Bios__Gender__c = 'Female',AccountId = acc.Id);
      mcc.detailContact = conList[0];
      mcc.cont.ReportsToId = conList[0].Id;
      
  
  //myPage.getParameters().put('contactWithRelatedObject',conList[1].id);
      Contact conUpdate = new Contact(Id = conList[1].Id , 
                                         Single_Household__c = conList[1].AccountId ,
                                         AccountId = conList[0].AccountId ,
                                         rC_Bios__Secondary_Contact__c = true,
                                         rC_Bios__Marital_Status__c = 'Married');
      upsert conUpdate; 
      mcc.contactRecord = conList[1];
      mcc.cancelOnClick();
      mcc.saveOnClick();
      mcc.saveForExistingContact();
      mcc.findExistingContact();
      mcc.fetchspouseDetails();
      mcc.getFields();
 	
 }   
}