src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SUID__c</fullName>
        <label>SUID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Manually populated field indicating is this account active?</description>
        <inlineHelpText>Is this account active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated via trigger (Lookup to Contact) when Preferred Contact is checked on the Contact record.</description>
        <inlineHelpText>Automatically populated via trigger (Lookup to Contact object) when Preferred Contact is checked on the Contact record.</inlineHelpText>
        <label>Preferred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Preferred Contact)</relationshipLabel>
        <relationshipName>Accounts_Preferred_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SUID__c</fullName>
        <description>S-340088</description>
        <externalId>true</externalId>
        <label>SUID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field directly populated by trigger reflecting thids account is active.</description>
        <inlineHelpText>Is this Contact active?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates Contact as Preferred for the Account. Contact data is automatically rolled up to Account as a result.</description>
        <inlineHelpText>Designates Contact as Preferred for the Account.</inlineHelpText>
        <label>Preferred Contact?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BIO_LogACallControllerTest.cls
/********************************************************************************************
* Apex Class Name: BIO_LogACallControllerTest
* Author: Appirio
* Date: [04/04/2016]
* Requirement Description: Test Class for BIO_LogACallController(T-488510/S-342662)
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
@isTest
private class BIO_LogACallControllerTest{
	
	static testMethod void bio_LogACallControllerTest() {
		List<Contact> conList = new List<Contact>();
		List<Contact> suidList = new List<Contact>();
 		Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
														.get('Household').getRecordTypeId();
		Account acc = new Account(Name = 'Test',
															RecordTypeId = devRecordTypeId,
															rC_Bios__Active__c= true);
		insert acc;

		
		 
		Contact con = new Contact(Salutation = 'Ms.',
																LastName = 'xyz',
																rC_Bios__Gender__c = 'Female',
																AccountId = acc.Id);
		conList.add(con);

		Contact conRecord = new Contact(Salutation = 'Mr.',
																		LastName = 'abc',
																		rC_Bios__Gender__c = 'Male',
																		AccountId = acc.Id,
																		rC_Bios__Preferred_Contact__c = true);
		conList.add(conRecord);

		insert conList;
		
		suidList = [SELECT id ,SUID__c FROM CONTACT WHERE id in :conList];
		String suid1= suidList[0].SUID__c;
		String suid2 = suidList[1].SUID__c;
		String suid ;
		PageReference pageRef = Page.BIO_LogACall;
    Test.setCurrentPage(pageRef);
    BIO_LogACallController interactionLog = new BIO_LogACallController();
    suid = suid1;
    suid += ','+ suid2;
   // suid += '9998989433';
    interactionLog.contactSuid = suid;
    interactionLog.onSave();
    interactionLog.onCancel();
    
    
   
  }
  static testMethod void bio_LogACallControllerTestInvalidSuid() {
  	
		PageReference pageRef = Page.BIO_LogACall;
    Test.setCurrentPage(pageRef);
    BIO_LogACallController interactionLog = new BIO_LogACallController();
     
    interactionLog.contactSuid = '6675894632';
    interactionLog.onSave();
    interactionLog.onCancel();
 
  }

        
}