src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SUID__c</fullName>
        <label>SUID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Manually populated field indicating is this account active?</description>
        <inlineHelpText>Is this account active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Category__c</fullName>
        <description>Manually populated field indicating the type of Organization.</description>
        <inlineHelpText>Indicates the type of Organization.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated via trigger (Lookup to Contact) when Preferred Contact is checked on the Contact record.</description>
        <inlineHelpText>Automatically populated via trigger (Lookup to Contact object) when Preferred Contact is checked on the Contact record.</inlineHelpText>
        <label>Preferred Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Preferred Contact)</relationshipLabel>
        <relationshipName>Accounts_Preferred_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Secondary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically populated via trigger (Lookup to Contact) when Secondary Contact is checked on the Contact record.</description>
        <inlineHelpText>Automatically populated via trigger (Lookup to Contact) when Secondary Contact is checked on the Contact record.</inlineHelpText>
        <label>Secondary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Secondary Contact)</relationshipLabel>
        <relationshipName>Accounts_Secondary_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SUID__c</fullName>
        <description>S-340088</description>
        <externalId>true</externalId>
        <label>SUID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Single_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>S-340070 - This Field is used to store the Single household that a Single contact is in.  It is used in casethe user gets married and later divorced as a pointer to their old single household.</description>
        <label>Single Household</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Household Account does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <infoMessage>Select the Contact&apos;s Single Household</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Single Contact</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field directly populated by trigger reflecting thids account is active.</description>
        <inlineHelpText>Is this Contact active?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Marital_Status__c</fullName>
        <description>Manually populated field indicating Contact&apos;s marital status.</description>
        <inlineHelpText>Indicates Contact&apos;s marital status.</inlineHelpText>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Marital Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domestic Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formerly Married/Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married At Death</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widowed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Preferred_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates Contact as Preferred for the Account. Contact data is automatically rolled up to Account as a result.</description>
        <inlineHelpText>Designates Contact as Preferred for the Account.</inlineHelpText>
        <label>Preferred Contact?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Secondary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Automatically populated via trigger when Secondary Contact is selecteed on the Account Manage Contacts Page.</description>
        <inlineHelpText>Indicates this Contact is the secondary Contact for their Account.</inlineHelpText>
        <label>Secondary Contact?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Work_Email__c</fullName>
        <description>Manually populated field indicating Contact&apos;s work email.</description>
        <inlineHelpText>Contact&apos;s work email address.</inlineHelpText>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Work_Phone__c</fullName>
        <description>Manually populated field indicating Contact&apos;s work phone number.</description>
        <inlineHelpText>Contact&apos;s work phone number.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MarriageComponentController.cls
/********************************************************************************************
* Apex Class Name: MarriageComponentControlleTest
* Author: Appirio
* Date: [04/04/2016]
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
public without sharing class MarriageComponentController {

    public contact cont{get;set;}
    public boolean checkContact{get;set;}
    public contact detailContact{get;set;}
    public boolean displayPanel{get;set;}
    public Contact contactRecord {get; set;}

    
    // Constructor
    public MarriageComponentController(){
        cont = new Contact();
        cont.rC_Bios__Marital_Status__c = 'Married';
        checkContact = true;
        displayPanel = false;
        
        
        
    }

    //**************************************************************************************************************** 
    //Method to fetch the fields from Field Set.
    //****************************************************************************************************************
    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.contact.FieldSets.rC_Bios__Account_ManageContacts.getFields();
    }


    
    //**************************************************************************************************************** 
    //Method to create new Contact and make changes in the existing contact  and Create Realtionship record
    //****************************************************************************************************************
    public PageReference saveOnClick(){
       
       
       
       try{
           Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
           Account houseHoldAccount = new Account(rC_Bios__Active__c = true ,
                                                    RecordTypeId = devRecordTypeId,
                                                    Name = 'New Account'    );
           
           insert houseHoldAccount;
           
           cont.AccountId = houseHoldAccount.Id;
           insert cont;
           contact contactToUpdate;
           if(contactRecord.rC_Bios__Preferred_Contact__c == true){
              contactToUpdate = new Contact(Id = contactRecord.Id , 
                                     Single_Household__c = contactRecord.AccountId ,
                                     AccountId = houseHoldAccount.Id ,
                                     rC_Bios__Secondary_Contact__c = true,
                                     rC_Bios__Marital_Status__c = 'Married');
           }else if(contactRecord.rC_Bios__Secondary_Contact__c == true){
             contactToUpdate  = new Contact(Id = contactRecord.Id , 
                                     Single_Household__c = contactRecord.AccountId ,
                                     AccountId = houseHoldAccount.Id ,
                                     rC_Bios__Preferred_Contact__c = true,
                                     rC_Bios__Marital_Status__c = 'Married'); 
           }
           
           
            upsert contactToUpdate;                         
               
                                                                
           createRelationship(contactToUpdate.Id ,cont.Id);
           
           PageReference pgRef = new PageReference('/' + contactToUpdate.id); 
           pgRef.setRedirect(true);
           return pgRef;  
           
           
       }
       catch(Exception e){
           System.debug('The following exception has occurred: ' + e.getMessage());
       }
       
       return null;
       
       
       
    }
    
    
    //**************************************************************************************************************** 
    //Method to make change in spouse contact and make changes in the existing contact  and Create Realtionship record
    //****************************************************************************************************************
     public PageReference saveForExistingContact(){
     
     //System.assert(false, '>>>' + contactRecord.AccountId + '@@@@' + detailContact);
     
     
     if(detailContact.rC_Bios__Marital_Status__c == 'Married'){
         
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'The Selected contact is already Married'));
         return null;
         
     }
     
     
     try{
         
             Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
             Account houseHoldAccount = new Account(rC_Bios__Active__c = true ,
                                                    RecordTypeId = devRecordTypeId,
                                                    Name = 'New Account' );
           
             insert houseHoldAccount;
             contact contactToUpdate;
             if(contactRecord != null){
             
                      /*   if(contactRecord.rC_Bios__Preferred_Contact__c == true){
                             contactToUpdate = new Contact(Id = contactRecord.Id , 
                                                 Single_Household__c = contactRecord.AccountId ,
                                                 AccountId = houseHoldAccount.Id ,
                                                 rC_Bios__Marital_Status__c = 'Married');
                        }else if(contactRecord.rC_Bios__Secondary_Contact__c == true){
                            contactToUpdate = new Contact(Id = contactRecord.Id , 
                                                 Single_Household__c = contactRecord.AccountId ,
                                                 AccountId = houseHoldAccount.Id ,
                                                 rC_Bios__Marital_Status__c = 'Married');
                       }*/
                         
             
             
             contactToUpdate = new Contact(Id = contactRecord.Id , 
                                     Single_Household__c = contactRecord.AccountId ,
                                     AccountId = houseHoldAccount.Id ,
                                     rC_Bios__Marital_Status__c = 'Married'); 
                                     
             upsert contactToUpdate; 
             createRelationship(contactToUpdate.Id , detailContact.Id);
             
             }
             
             PageReference pgRef = new PageReference('/' + contactToUpdate.id); 
             pgRef.setRedirect(true);
             return pgRef;
         }catch(Exception e){
             System.debug('The following exception has occurred: ' + e.getMessage());
            }
     
        return null;
     
     
     
     }
    
    
    //**************************************************************************************************************** 
    //Method to redirect to contact page upon Cancel.
    //****************************************************************************************************************
    
    public PageReference cancelOnClick(){
         PageReference pgRef = new PageReference('/' + contactRecord.id); 
         pgRef.setRedirect(true);
         return pgRef;
    }
    
   //**************************************************************************************************************** 
    //Method to moderate the boolean variable to toggle panels 
    //****************************************************************************************************************
    
    public void findExistingContact(){
        //System.assert(false,'>>>' + checkContact);
        if(checkContact == true){
            displayPanel = true;
        }else{
             displayPanel = false;
        }
        
        
    }
    
    //**************************************************************************************************************** 
    //Method to fetch the spouse details upon select 
    //****************************************************************************************************************
    
    public void fetchspouseDetails(){
        //System.assert(false,'>>>' + cont.ReportsToId);
        detailContact = new Contact();
        detailContact = [Select Id, SUID__c , AccountId, Account.Name ,  Single_Household__c, rC_Bios__Work_Email__c , rC_Bios__Gender__c ,
                                            rC_Bios__Active__c , rC_Bios__Marital_Status__c ,rC_Bios__Work_Phone__c
                                            From Contact where Id = : cont.ReportsToId];
        
        //System.assert(false,'>>>' +detailContact);
        
        
    }
    
    //**************************************************************************************************************** 
    //Method to create the relation record between two contacts.
    //****************************************************************************************************************
    
    private void createRelationship(Id SpouseContactId , Id currentContactId){
        try{
            Id devRecordTypeId = Schema.SObjectType.rC_Bios__Relationship__c.getRecordTypeInfosByName().get('Contact - Contact').getRecordTypeId();
            rC_Bios__Relationship__c realtion = new rC_Bios__Relationship__c(rC_Bios__Category__c = 'Family' ,
                                                                            rC_Bios__Role_1__c = 'Partner' ,
                                                                            rC_Bios__Role_2__c = 'Spouse',
                                                                            rC_Bios__Contact_1__c = currentContactId,
                                                                            rC_Bios__Contact_2__c = SpouseContactId,
                                                                            rC_Bios__Active__c = true,
                                                                            RecordTypeId = devRecordTypeId);
        
        insert realtion;
            
        }catch(Exception e){
            
        }
        
        
        
        
        
        
        
    }
    
    
}