src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Manually populated field indicating is this account active?</description>
        <inlineHelpText>Is this account active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Single_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>S-340070 - This Field is used to store the Single household that a Single contact is in.  It is used in casethe user gets married and later divorced as a pointer to their old single household.</description>
        <label>Single Household</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Household Account does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <infoMessage>Select the Contact&apos;s Single Household</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Single Contact</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field directly populated by trigger reflecting thids account is active.</description>
        <inlineHelpText>Is this Contact active?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Marital_Status__c</fullName>
        <description>Manually populated field indicating Contact&apos;s marital status.</description>
        <inlineHelpText>Indicates Contact&apos;s marital status.</inlineHelpText>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Marital Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domestic Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formerly Married/Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married At Death</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widowed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Manage_Life_Event_ControllerTest.cls
/********************************************************************************************
* Apex Class Name: Manage_Life_Event_ControllerTest
* Author: Appirio
* Date: [04/04/2016]
* Requirement Description: Test Class for MarriageComponentControlle (T-489404/S-372714)
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
@isTest

private class Manage_Life_Event_ControllerTest {
    static testMethod void testOne() {
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
     	List<Account> accList = new List<Account>();
     	Account acc = new Account(Name = 'Test',RecordTypeId = devRecordTypeId,rC_Bios__Active__c= true);
     	accList.add(acc);
     	Account acc1 = new Account(Name = 'Test Acc',RecordTypeId = devRecordTypeId);
     	accList.add(acc1);
     	Account acc2 = new Account(Name = 'Married Account',RecordTypeId = devRecordTypeId);
     	accList.add(acc2);
     	Account acc3 = new Account(Name = 'Married Account',RecordTypeId = devRecordTypeId);
     	accList.add(acc3);
     	insert accList;
     	
     	List<Contact> conList = new List<Contact>();
     	Contact con = new Contact(Salutation = 'Ms.',LastName = 'xyz',rC_Bios__Gender__c = 'Female',AccountId = acc.Id);
        conList.add(con);
        Contact conRecord = new Contact(Salutation = 'Mr.',LastName = 'abc',rC_Bios__Gender__c = 'Male',AccountId = acc1.Id);
        conList.add(conRecord);
        Contact conRecord2 = new Contact(Salutation = 'Mr.',LastName = 'abc',rC_Bios__Gender__c = 'Male',AccountId = acc2.Id,rC_Bios__Marital_Status__c = 'Married');
        conList.add(conRecord2);
        Contact conRecord3 = new Contact(Salutation = 'Mr.',LastName = 'abc',rC_Bios__Gender__c = 'Male',AccountId = acc2.Id,rC_Bios__Marital_Status__c = 'Married');
        conList.add(conRecord3);
        Contact conRecord4 = new Contact(Salutation = 'Mr.',LastName = 'abc',rC_Bios__Gender__c = 'Male',AccountId = acc3.Id,
                                            rC_Bios__Marital_Status__c = 'Married',Single_Household__c = acc.Id);
        conList.add(conRecord4);
        Contact conRecord5 = new Contact(Salutation = 'Mr.',LastName = 'abc',rC_Bios__Gender__c = 'Male',AccountId = acc3.Id,
                                        rC_Bios__Marital_Status__c = 'Married',Single_Household__c = acc1.Id);
        conList.add(conRecord5);
        insert conList;
        Manage_Life_Event_Controller controller = new Manage_Life_Event_Controller(new ApexPages.StandardController(conList[0]));
        controller.getFields();
        controller.cont.LastName = 'Test';
        controller.cont.rC_Bios__Gender__c = 'Male';
        controller.saveOnClick();
        controller.showerrorMessage();
        controller.cancelOnClick();
        controller.cont.ReportsToId = conList[1].Id;
        controller.fetchspouseDetails();
        controller.saveForExistingContact();
        controller.spouseDetailBeforeMarriage();
        Manage_Life_Event_Controller controller2 = new Manage_Life_Event_Controller(new ApexPages.StandardController(conList[2]));
        controller2.divorceSpouseDetails();
        test.startTest();
        Manage_Life_Event_Controller controller3 = new Manage_Life_Event_Controller(new ApexPages.StandardController(conList[4]));
        controller3.divorceSpouseDetails();
        test.stopTest();
        
        
        
        
        
        
        
        
    }
}