src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>APP_Suffix__c</fullName>
        <description>S-366408</description>
        <inlineHelpText>Personal Suffix</inlineHelpText>
        <label>Suffix</label>
        <picklist>
            <picklistValues>
                <fullName>Jr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIII</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Est.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Marital_Status__c</fullName>
        <description>Manually populated field indicating Contact&apos;s marital status.</description>
        <inlineHelpText>Indicates Contact&apos;s marital status.</inlineHelpText>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Marital Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domestic Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formerly Married/Partnered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married At Death</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widowed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rC_Bios__Middle_Name__c</fullName>
        <description>Manually populated field indicating Contact&apos;s middle name.</description>
        <inlineHelpText>Contact&apos;s middle name.</inlineHelpText>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <description>T-467757</description>
        <inlineHelpText>Select one or more groups that are collaborating on this specific proposal</inlineHelpText>
        <label>Group</label>
        <picklist>
            <picklistValues>
                <fullName>Alumni Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts Initiative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-X/Neuro/ChEM-H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Center for Advanced Study in the Beh Sci</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clayman Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earth Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freeman Spogli Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H&amp;S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haas Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoover House Circle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Libraries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lively Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Longevity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Museum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Next Generation Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIEPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stanford Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Strategy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related strategy for this proposal</description>
        <label>Strategy</label>
        <referenceTo>Strategy__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategy__c.object
<CustomObject>
    <description>T-459059</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>T-464755</description>
        <inlineHelpText>Account associated with this strategy</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <infoMessage>This filter defaults to a HOUSEHOLD search remove the criteria filter to search for ORGANIZATIONS</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategies</relationshipLabel>
        <relationshipName>Strategies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <description>Overall goal of strategy</description>
        <inlineHelpText>Outline your: Strategy/goal/use case/plan/Communication methodology/events/emails http://merskyjaffe.com/general-fundraising/develop-strategic-solicitation-strategy/</inlineHelpText>
        <label>Goal</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <defaultValue>&quot;Outline your: Strategy/goal/use case/plan/Communication methodology/events/emails&quot;</defaultValue>
        <description>What are the main steps to accomplishing the strategy</description>
        <inlineHelpText>What are the main steps to accomplishing the strategy</inlineHelpText>
        <label>Plan</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Strategies</relationshipLabel>
        <relationshipName>Strategies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandlerTest.cls
/********************************************************************************************
* Trigger Name: OpportunityTriggerHandlerTest
* Author: Rahul Khanchandani (Appirio)
* Date: [11/02/2016]
* Requirement Description: Test Class for OpportunityTriggerHandler Class Created 
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
@isTest
public class OpportunityTriggerHandlerTest {
    private static testMethod void opportunityTriggerHandlerTest(){
 			Id devRecordTypeId =Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
								.get('Proposal').getRecordTypeId();
 			 User u = createUser('OOD User',false);
       insert u;
       System.runAs(u)
       {  
       		Account acc = new Account(Name = 'TestAcc');
       		Account acc1 = new Account(Name = 'TestAcc1');
       		insert acc;
       		insert acc1;
       	
       		List<Contact> conList = new List<Contact>();
					Contact con0 = new Contact(Salutation = 'Ms.',FirstName = 'abc',LastName = 'xyz1',rC_Bios__Middle_Name__c = 'rst2',APP_Suffix__c = 'Jr.',rC_Bios__Gender__c = 'Female',AccountId = acc.id,rC_Bios__Marital_Status__c = 'Widowed');
					Contact con1 = new Contact(Salutation = 'Ms.',FirstName = 'abc',LastName = 'xyz',rC_Bios__Middle_Name__c = 'rst',APP_Suffix__c = 'Jr.',rC_Bios__Gender__c = 'Female',AccountId = acc1.id,rC_Bios__Marital_Status__c = 'Widowed');
					conList.add(con0);
					conList.add(con1);
					insert conList;
       		
       		Strategy__c st = new Strategy__c();
       		st.Name = 'Test Strategy';
       		st.Account__c = acc.Id;
       		st.Prospect__c = conList[0].Id;
       		st.Goal__c = 'Strategy Goal';
       		st.Plan__c = 'Strategy Plan';
       		insert st;
       		
       		Strategy__c st1 = new Strategy__c();
       		st1.Name = 'Test Strategy1';
       		st1.Account__c = acc1.Id;
       		st1.Prospect__c = conList[1].Id;
       		st1.Goal__c = 'Strategy Goal1';
       		st1.Plan__c = 'Strategy Plan1';
       		insert st1;
       		
       		Opportunity opp = new Opportunity();
		    	opp.Name = 'OppTest1';
		    	opp.Group__c = 'OppTest';
		    	opp.StageName = 'OppTest';
		    	opp.CloseDate = System.today()+5;
		    	opp.RecordTypeId = devRecordTypeId;
		    	opp.Strategy__c= st.id;

					Opportunity opp1 = new Opportunity();
		    	opp1.Name = 'OppTest1OppTest1OppTest1OppTest1OppTest1OppTest1OppTest2OppTest3OppTest4OppTest5OppTest6';
		    	opp1.Group__c = 'OppTest,OppTest2,OppTest3,OppTest4';
		    	opp1.StageName = 'OppTest';
		    	opp1.CloseDate = System.today()+7;
		    	opp1.RecordTypeId = devRecordTypeId;
		    	opp1.Strategy__c= st1.id;

					List<Opportunity> resultOpportunityList = new List<Opportunity>();
					Test.startTest();
		    	insert opp;
		    	insert opp1;
		    	resultOpportunityList = [Select Name,Group__c from Opportunity];
		    	System.assertEquals(resultOpportunityList[0].Name,'OppTest1-OppTest');
       	}
    }
     public static User createUser(String profileName, Boolean isInsert){
        Profile p;
        List<Profile> listProfile = [SELECT Id FROM profile WHERE Name like :'%'+profileName+'%'];
        if(listProfile.size() > 0) {
            p = listProfile[0];
        } else {
            return null;
        }
        User testUser = new User(alias = 'testUser', email='standarduser' + Math.random()  + '@testorg.com',
                                emailencodingkey='UTF-8', lastname='Test', languagelocalekey='en_US',
                                localesidkey='en_US', profileid = p.Id, timezonesidkey='America/Los_Angeles',
                                username='teststandarduser' + Math.random() + '@testorg.com', IsActive=true,
                                Extension='1234', CompanyName = 'test Company');
        if(isInsert){
            insert testUser;
        }
        return testUser;
    }
}