src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>rC_Bios__Gender__c</fullName>
        <description>Manually populated field indicating Gender of a Contact.</description>
        <inlineHelpText>Indicates Gender of a Contact</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Report__c.object
<CustomObject>
    <description>T-476855</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>T-476856</description>
        <inlineHelpText>Household or Organization</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Reports</relationshipLabel>
        <relationshipName>Contact_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Reports (Contact2)</relationshipLabel>
        <relationshipName>Contact_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>T-476861</description>
        <label>Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>T-476856</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Reports</relationshipLabel>
        <relationshipName>Contact_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>T-476856</description>
        <inlineHelpText>Enter the descriptive subject of the interaction</inlineHelpText>
        <label>Subject</label>
        <length>144</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contact Report</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact2)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>T-467757</description>
        <inlineHelpText>Select one or more groups that are collaborating on this specific proposal</inlineHelpText>
        <label>Group</label>
        <picklist>
            <picklistValues>
                <fullName>Alumni Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts Initiative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-X/Neuro/ChEM-H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Center for Advanced Study in the Beh Sci</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clayman Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earth Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freeman Spogli Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H&amp;S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haas Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoover House Circle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Libraries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lively Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Longevity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Museum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Next Generation Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIEPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stanford Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Strategy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related strategy for this proposal</description>
        <label>Strategy</label>
        <referenceTo>Strategy__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rC_Giving__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Main contact at Grantor agency.</description>
        <inlineHelpText>Main contact at Grantor agency.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Giving(Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategy__c.object
<CustomObject>
    <description>T-459059</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>T-464755</description>
        <inlineHelpText>Account associated with this strategy</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <infoMessage>This filter defaults to a HOUSEHOLD search remove the criteria filter to search for ORGANIZATIONS</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategies</relationshipLabel>
        <relationshipName>Strategies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TBD</description>
        <label>Contact2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Strategies2</relationshipLabel>
        <relationshipName>Strategies2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <description>Overall goal of strategy</description>
        <inlineHelpText>Outline your: Strategy/goal/use case/plan/Communication methodology/events/emails http://merskyjaffe.com/general-fundraising/develop-strategic-solicitation-strategy/</inlineHelpText>
        <label>Goal</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <defaultValue>&quot;Outline your: Strategy/goal/use case/plan/Communication methodology/events/emails&quot;</defaultValue>
        <description>What are the main steps to accomplishing the strategy</description>
        <inlineHelpText>What are the main steps to accomplishing the strategy</inlineHelpText>
        <label>Plan</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Strategies</relationshipLabel>
        <relationshipName>Strategies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AddRelatedContactTest.cls
/********************************************************************************************
* Apex Class Name: AddRelatedContactsTest
* Author: Rahul Khanchandani (Appirio)
* Date: [28/03/2016]
* Requirement Description: Test Class for AddRelatedContact (T-483161/S-347760)
* Date Modified                Modified By                  Description of the update

***********************************************************************************************/
@isTest 
public with sharing class AddRelatedContactTest {
	//private members
	private static String recTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
  
  //Testing Add Related Contacts on Contact Report  
  public static testMethod void testAddRelatedContactFromContactReport(){
    	//Creating Account
  	Account acc = new Account(Name = 'Test Account');
		insert acc;
		List<Contact> conList = new List<Contact>();
		Contact cnt0 =  new Contact(Salutation = 'Ms.',FirstName = 'Test' , LastName = ' Contact',
																 accountId = acc.id,rC_Bios__Gender__c = 'Female',
																 recordTypeId = recTypeId);
		Contact cnt1 =  new Contact(Salutation = 'Mr.',FirstName = 'Test1' , LastName = ' Contact1',
																 accountId = acc.id,rC_Bios__Gender__c = 'Male',
																 recordTypeId = recTypeId);
		conList.add(cnt0);
		conList.add(cnt1);
    insert conList;
    
		//Creating Contact Report Test Data
		Contact_Report__c  conReport= new Contact_Report__c();
    conReport.Contact_Date__c = System.today();
    conReport.Subject__c = 'Test Contact Report';
    conReport.Account__c = acc.Id;
    insert conReport;
    	
    Test.startTest();
    AddRelatedContacts.populateContactField(conReport.Id,'Contact_Report__c',
    																					conReport.Account__c,'','', 'Contact__c', 'Contact2__c');
  	Test.stopTest();
   		
   	Contact_Report__c resultContactReport = [SELECT contact__r.Name FROM Contact_Report__c WHERE Id =: conReport.Id LIMIT 1];
    System.assertEquals('Test1 Contact1',resultContactReport.contact__r.Name);
    
  }
  
 //Testing Add Related Contacts on Strategy
 	public static testMethod void testAddRelatedContactReportFromStrategy(){
		//Creating Account
		Account acc1 = new Account(Name = 'Test Account1');
			insert acc1;
		
		List<Contact> conList = new List<Contact>();
		
		//Creating Contact Associated with Inserted Account
		Contact cnt0 =  new Contact(Salutation = 'Ms.',FirstName = 'Test' , LastName = ' Contact',
																accountId = acc1.id,rC_Bios__Gender__c = 'Female',recordTypeId = recTypeId);
		
		Contact cnt1 =  new Contact(Salutation = 'Mr.',FirstName = 'Test1' , LastName = ' Contact1'   , 
																accountId = acc1.id,rC_Bios__Gender__c = 'Male',recordTypeId = recTypeId);
		conList.add(cnt0);
		conList.add(cnt1);
		insert conList;
			
		//Creating Strategy  Test Data
		Strategy__c  strategy= new Strategy__c();
		strategy.Name = 'Test Strategy Name';
		strategy.Goal__c = 'Test Strategy Goal';
		strategy.Account__c = acc1.Id;
		strategy.Prospect__c = conList[0].Id;
		insert strategy;
		
		Test.startTest();
		AddRelatedContacts.populateContactField(strategy.Id,'Strategy__c',strategy.Account__c,strategy.Prospect__c,'',
																					 'Prospect__c', 'Contact2__c');
		Test.stopTest(); 
		Strategy__c resultStrategy = [SELECT Contact2__r.Name FROM Strategy__c WHERE Id =: strategy.Id LIMIT 1];
    System.assertEquals('Test1 Contact1',resultStrategy.Contact2__r.Name);
 }
 
 //Testing Add Related Contacts on Strategy
	public static testMethod void testAddRelatedContactFromTeam(){
		//Creating Team  Test Data
		rC_Education__Team__c  team= new rC_Education__Team__c();
		team.Name = 'Test Team';
		team.Group__c = 'EDU - Education';
		team.Program__c  = 'PAR - Parents';
		team.Group__c = 'Research';
		insert team;
		
		Test.startTest();
		String result = AddRelatedContacts.populateContactField(team.Id,'rC_Education__Team__c','','','',
																														'rC_Education__Contact__c', 'Contact2__c');
		Test.stopTest();
		
		System.assertEquals('Please populate account first to populate the contact information',result);
 }

  //Testing Add Related Contacts on Contact Report  
  public static testMethod void testAddRelatedContactFromContactReport1(){
  	Id devRecordTypeId =Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
								.get('Proposal').getRecordTypeId();
    //Creating Account
		Account acc1 = new Account(Name = 'Test Account1');
		insert acc1;
		
		List<Contact> conList = new List<Contact>();
			
		//Creating Contact Associated with Inserted Account
		Contact cnt0 =  new Contact(Salutation = 'Ms.',FirstName = 'Test' , LastName = ' Contact',
																	accountId = acc1.id,rC_Bios__Gender__c = 'Female',
																	recordTypeId = recTypeId);
			
		Contact cnt1 =  new Contact(Salutation = 'Mr.',FirstName = 'Test1' , 
																LastName = ' Contact1'   , accountId = acc1.id,
																rC_Bios__Gender__c = 'Male',recordTypeId = recTypeId);
		conList.add(cnt0);
		conList.add(cnt1);
		insert conList;
		//Creating Strategy For Associatiing With Opportunity
	/*	Strategy__c st = new Strategy__c();
  	st.Name = 'Test Strategy';
  	st.Account__c = acc1.Id;
  	st.Prospect__c = conList[0].Id;
  	st.Goal__c = 'Strategy Goal';
  	st.Plan__c = 'Strategy Plan';
  	insert st;
			
		//Creating Opportunity Test Data
		Opportunity opp = new Opportunity();
   	opp.Name = 'OppTest1';
   	opp.Group__c = 'OppTest';
   	opp.StageName = 'OppTest';
   	opp.CloseDate = System.today()+5;
   	opp.Account = acc1;
   	opp.rC_Giving__Primary_Contact__c = conList[0].id;
   	opp.Contact2__c = conList[1].id;
   	opp.Strategy__c= st.id;
   	opp.RecordTypeId = devRecordTypeId;
   	insert opp;
    	*/
    	
    	//Creating Contact Report Test Data
		Contact_Report__c  conReport= new Contact_Report__c();
    conReport.Contact_Date__c = System.today();
    conReport.Subject__c = 'Test Contact Report';
    conReport.Account__c = acc1.Id;
    conReport.Contact__c = conList[0].id;
    conReport.Contact2__c = conList[1].id;
    insert conReport;
    	
    Test.startTest();
    String resultError = AddRelatedContacts.populateContactField(conReport.Id,'Contact_Report__c',
    																					conReport.Account__c, conReport.Contact__c, conReport.Contact2__c, 'Contact__c', 'Contact2__c');
  	Test.stopTest();
    	
    	
   
    System.assertEquals('Both primary and secondary Contacts are already populated',resultError);
    
  }

 }