src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SUID_Pool_Value__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>SUID Pool Value</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>SUID__c</fullName>
        <description>S-340088</description>
        <externalId>true</externalId>
        <label>SUID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SUID_GeneratorServiceContact.cls
//
// (c) 2016 Appirio, Inc.
//
// An apex class update SUID on Contact (method gets invoked from process builder)
//
// 1st March, 2016     Sudhir Kumar Jagetiya       Original
//
public class SUID_GeneratorServiceContact {
	@InvocableMethod
	// @description: A method that Update SUID on Contact.
  // @param: List<Id> list of contact ids that need to be updated with SUID
  // @return void
	public static void updateSUIDonContact(List<Id> contactIds) {
    List<Contact> contactNeedToBeUpdated = [SELECT Id, SUID_Pool_Value__c
                                              FROM Contact
                                             WHERE Id IN:contactIds
                                               AND SUID_Pool_Value__c != null];
    for(Contact con : contactNeedToBeUpdated) {
        con.SUID__c = SUID_GeneratorService.getNextSUID(con.SUID_Pool_Value__c, '02');
    }
    update contactNeedToBeUpdated;
	}
}