src/objects/Contact_Report__c.object
<CustomObject>
    <description>T-476855</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>T-476856</description>
        <label>Author</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Contact Reports</relationshipLabel>
        <relationshipName>Contact_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>T-476861</description>
        <label>Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>T-476856</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Reports</relationshipLabel>
        <relationshipName>Contact_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>T-476856</description>
        <label>Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney for Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Article/Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>T-476856</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-person visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other contact type (text, IM, etc.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-person contact at a group event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up Planned Giving Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Planned Giving Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Planned Giving Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Report</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Contact Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SS_DisplayInteractionHistory_AC.cls
/********************************************************************************************
* Class Name: SS_DisplayInteractionHistory_AC
* Author: Aditi Bhardwaj (Appirio)
* Date: [7/4/2016]
* Requirement Description: Extension class for SS_DisplayInteractionHistory page
* Date Modified                Modified By                  Description of the update
************************************************************************************************/

public with sharing class SS_DisplayInteractionHistory_AC {
    
    // List will hold data to display on page
    public List<DisplayInteractionHistoryWrapper> contactIntractionHistoryList {get;set;}
    
    
 
  // Constructor
  public SS_DisplayInteractionHistory_AC(ApexPages.StandardController stdController){
    String contactId;
    if(stdController != null){
            contactId = stdController.getId();
    }
    if(!String.isBlank(contactId)){
        contactIntractionHistoryList = populateInteractionHistory(contactId);
    }
  }

  // This method populates contactIntractionHistoryList with 
  // contact report and log a call activity records
  private List<DisplayInteractionHistoryWrapper> populateInteractionHistory(
        String contactId
    ){
    List<DisplayInteractionHistoryWrapper> tempHistoryList = 
            new List<DisplayInteractionHistoryWrapper>();
    
    List<Contact_Report__c> contactReportList = new List<Contact_Report__c>();
    List<Task> logACallActivityList = new List<Task>(); 
    contactIntractionHistoryList = new List<DisplayInteractionHistoryWrapper>();
    
    // Get contact report records
    contactReportList = [SELECT id,Purpose__c,Type__c   ,
                                                            Author__r.Name,Contact_Date__c
                                                FROM Contact_Report__c 
                                                WHERE Contact__c = :contactId
                                                ORDER BY Contact_Date__c ASC NULLS LAST
                                                LIMIT 50];

        
        // Get log a call activity records
        logACallActivityList = [SELECT id,Subject,ActivityDate,
                                                                        CreatedBy.Name,Status,Type
                                                        FROM Task
                                                        WHERE WhoId = :contactId
                                                        AND
                                                        Status = :SalutationConstants.COMPLETED
                                                        AND Subject = :SalutationConstants.CALL
                                                        ORDER BY ActivityDate   ASC NULLS LAST
                                                        LIMIT 50];                                      
        

        // Adding contact report records in temporary list
        
        for(Contact_Report__c temp : contactReportList){
            tempHistoryList.add(new DisplayInteractionHistoryWrapper(
                
                temp.id,
                'Contact Report',
                temp.Type__c,
                temp.Contact_Date__c,
                temp.Author__r.Name,
                temp.Purpose__c
                )
            );
        }
        
        // Adding logACallActivity records in temporary list
        
            for(Task temp : logACallActivityList){
                tempHistoryList.add(new DisplayInteractionHistoryWrapper(
                      temp.id,
                      'Activity',
                      temp.Subject,
                      temp.ActivityDate,
                      temp.CreatedBy.Name,
                      ''
                  )
                );
            }
    
        // Sorting records in list on the basis of date
        tempHistoryList.sort();

        // Populating contactIntractionHistoryList with 
        // first 50 records of temporary list
        
        for(Integer index = 0 ; index < 50  && index < tempHistoryList.size() ;index ++){
            
                contactIntractionHistoryList.add(tempHistoryList[index]);
        }

        return contactIntractionHistoryList;


  }

  
  
 // Wrapper class contains Payment History info to be display.
  public class DisplayInteractionHistoryWrapper implements Comparable {
        
    public id recordId {get;set;}
    public String recordType {get;set;}
    public String type {get;set;}
    public Date interactionDate {get; set;}
    public String author {get; set;}
    public String purpose {get; set;}
        
    
    // Constructor
    public DisplayInteractionHistoryWrapper(id recordId, String recordType, String type,
                                                                                    Date interactionDate,
                                                                                    String author, 
                                                                                    String purpose){
        this.recordId = recordId;
        this.recordType = recordType;                                                                    
        this.type = type;
        this.interactionDate = interactionDate;
        this.author = author;
        this.purpose =purpose;
     
    }

    // Performing sorting on basis of date
    public  Integer compareTo(Object objToCompare){
        if(interactionDate > (((DisplayInteractionHistoryWrapper)objToCompare).interactionDate)){
            return 1;
        }else if(interactionDate < (((DisplayInteractionHistoryWrapper)objToCompare).interactionDate)){
            return -1;  
        }else{
            return 0;
        }
        
       }

   

  }

  
}